import { Link } from "wouter";
import { Mail, MapPin, Phone } from "lucide-react";
import { CONTACT } from "@/lib/contact";
import { useSEO } from "@/lib/use-seo";

const wordmark = "/logo-wordmark.webp";

const copy = {
  about: { title: "About Cliffhanger", description: "Cliffhanger has supplied certified climbing and outdoor equipment in Lebanon since 2003.", heading: "Made for the vertical", body: "Cliffhanger is a Lebanon-based climbing equipment specialist. Since 2003, we have helped climbers choose certified hardware, ropes, helmets, shoes, and accessories with clear manufacturer specifications and direct product support." },
  partners: { title: "Official Climbing Gear Partners | Cliffhanger", description: "Meet Cliffhanger's official climbing equipment partners: Edelrid and Tendon.", heading: "Official partners", body: "Cliffhanger stocks equipment from EDELRID of Germany and TENDON of the Czech Republic. Their certified climbing hardware and ropes are represented across our catalog; each product page identifies its technical information and certification where provided by the manufacturer." },
  contact: { title: "Contact Cliffhanger | Climbing Gear Lebanon", description: "Contact Cliffhanger in Lebanon for climbing equipment availability, product specifications, and gear enquiries.", heading: "Contact Cliffhanger", body: "For product availability, technical details, or a climbing gear enquiry, contact the Cliffhanger team by WhatsApp, phone, or email. We are based in Lebanon." },
} as const;

export default function CompanyPage({ page }: { page: keyof typeof copy }) {
  const content = copy[page];
  useSEO({ title: content.title, description: content.description, path: `/${page}` });
  return <div className="min-h-screen bg-black text-white font-sans"><a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-3 focus:top-3 focus:z-[100] focus:bg-primary focus:px-4 focus:py-2 focus:font-mono focus:text-xs focus:uppercase focus:tracking-widest focus:text-black">Skip to content</a><header className="sticky top-0 flex items-center justify-between border-b border-border bg-black/90 px-5 py-4"><Link href="/" className="flex min-h-11 items-center"><img src={wordmark} alt="Cliffhanger" width={812} height={184} className="h-7 w-auto" /></Link><Link href="/products" className="inline-flex min-h-11 items-center px-2 font-mono text-xs uppercase tracking-widest text-gray-300 hover:text-primary">Catalog</Link></header><main id="main" tabIndex={-1} className="mx-auto max-w-4xl px-6 py-20 md:py-28"><p className="font-mono text-xs uppercase tracking-[0.25em] text-primary">Cliffhanger · Lebanon</p><h1 className="mt-4 text-5xl font-bold uppercase tracking-tighter md:text-7xl">{content.heading}</h1><p className="mt-8 max-w-3xl font-mono text-base leading-relaxed text-gray-300">{content.body}</p>{page === "partners" && <section className="mt-16 grid gap-5 md:grid-cols-2"><article className="border border-border p-8"><h2 className="text-3xl font-bold uppercase">Edelrid</h2><p className="mt-4 font-mono text-sm leading-relaxed text-gray-300">Climbing and safety equipment partner from Germany, represented in Cliffhanger's hardware, PPE, and accessory catalog.</p></article><article className="border border-border p-8"><h2 className="text-3xl font-bold uppercase">Tendon</h2><p className="mt-4 font-mono text-sm leading-relaxed text-gray-300">Rope manufacturer from the Czech Republic, represented in Cliffhanger's climbing rope selection.</p></article></section>}{page === "contact" && <section className="mt-16 grid gap-4"><a href={CONTACT.whatsapp} className="border border-primary bg-primary p-6 font-mono text-sm font-bold uppercase tracking-widest text-black">WhatsApp Cliffhanger</a><a href={CONTACT.tel} className="flex items-center gap-4 border border-border p-6 font-mono text-sm hover:border-primary"><Phone className="text-primary" /> {CONTACT.phoneDisplay}</a><a href={`mailto:${CONTACT.email}`} className="flex items-center gap-4 border border-border p-6 font-mono text-sm hover:border-primary"><Mail className="text-primary" /> {CONTACT.email}</a><div className="flex items-center gap-4 border border-border p-6 font-mono text-sm"><MapPin className="text-primary" /> Lebanon</div></section>}<div className="mt-16"><Link href="/products" className="font-mono text-xs uppercase tracking-widest text-primary hover:text-white">Browse climbing gear →</Link></div></main></div>;
}
